services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: oxygenial
      POSTGRES_PASSWORD: oxygenial
      POSTGRES_DB: oxygenial
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
